services:
  app:
    container_name: import-csv-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3333'
    depends_on:
      - mongodb
    env_file:
      - .env
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    container_name: import-csv-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: importcsv
    restart: unless-stopped

volumes:
  mongo_data:
