export interface AlteracaoTitularDTO {
    tipoAlteracao?: string
    contrato?: string
    subfatura?: string
    operadora?: string
    dataInicioVigencia?: Date
    dataInicioVigenciaProgramada?: Date
    matricula?: string
    certificado?: string
    matriculaNova?: string
    centroCustoNovo?: string
    comeCentroCustoNovo?: string
    planoNovo?: string
    motivoAlteracaoPlano?: string
    nomeTitularCadastrado?: string
    nomeTitularCorreto?: string
    dataNascimentoCadastrada?: Date
    dataNascimentoCorreta?: Date
    estadoCivil?: string
    peso?: string
    altura?: string
    cpfCadastrado?: string
    cpfCorreto?: string
    nomeMaeCorreto?: string
    nomePaiCorreto?: string
    tipoLogradouro?: string
    nomeLogradouro?: string
    numeroLogradouro?: string
    complementoLogradouro?: string
    bairroLogradouro?: string
    cidadeLogradouro?: string
    estadoLogradouro?: string
    cepLogradouro?: string
    banco?: string
    agencia?: string
    digitoAgencia?: string
    contaCorrente?: string
    digitoContaCorrente?: string
    telefone?: string
    email?: string
    loteChamado?: string
    documento?: string
    sequencia?: string
    setor?: string
    lotacao?: string
    local?: string
    unidadeAtendimento?: string
    unidadeNegociacao?: string
}
