export interface InclusaoGrupoFamiliarDTO {
    operadora?: string
    contrato?: string
    subfatura?: string
    dataInicioVigencia?: Date
    datainicioVigenciaProgramada?: Date
    plano?: string
    matricula?: string
    codigoDependente?: string
    dataAdmissao?: Date
    nomeSegurado?: string
    sexo?: string
    dataNascimento?: Date
    cpf?: string
    estadoCivil?: string
    grauParentesco?: string
    peso?: string
    altura?: string
    dataTutela?: Date
    dataDocumento?: Date
    dataCasamento?: Date
    nomeMae?: string
    nomePai?: string
    pis?: string
    rg?: string
    orgaoEmissor?: string
    dataExpedicao?: Date
    centroCusto?: string
    nomeCentroCusto?: string
    cargo?: string
    tipoLogradouro?: string
    nomeLogradouro?: string
    numeroLogradouro?: string
    complementoLogradouro?: string
    bairroLogradouro?: string
    cidadeLogradouro?: string
    estadoLogradouro?: string
    cepLogradouro?: string
    cartaoNacionalSaude?: string
    banco?: string
    agencia?: string
    digitoAgencia?: string
    contaCorrente?: string
    digitoContaCorrente?: string
    numeroNascidoVivo?: string
    telefone?: string
    email?: string
    loteChamado?: string
    documento?: string
    sequencia?: string
    setor?: string
    lotacao?: string
    local?: string
    unidadeAtendimento?: string
    unidadeNegociacao?: string
}
  