export interface InclusaoDependenteDTO {
    operadora?: string
    contrato?: string
    subfatura?: string
    matriculaTitular?: string
    certificado?: string
    codigoDependente?: string
    nomeTitular?: string
    cpfTitular?: string
    nomeDependente?: string
    cpfDependente?: string
    dataNascimento?: Date
    sexo?: string
    estadoCivil?: string
    grauParentesco?: string
    peso?: string
    altura?: string
    dataTutela?: Date
    dataDocumento?: Date
    dataCasamento?: Date
    dataInicioVigencia?: Date
    datainicioVigenciaProgramada?: Date
    nomeMae?: string
    nomePai?: string
    numeroNascidoVivo?: string
    cartaoNacionalSaude?: string
    loteChamado?: string
    documento?: string
    sequencia?: string
    setor?: string
    lotacao?: string
    local?: string
}
